### PR TITLE
Fixes #58 - Allow casting Java objects to other types

### LINKED ISSUE #58: Add ability to cast objects to different classes
**Is your feature request related to a problem? Please describe.**

Some Java methods return `java.lang.Object`, and expect the end user to cast the return type into the object type they need. For example, Android's `getSystemService()` method returns java.lang.Object, but the underlying objects are types like `android.content.ClipboardManager`.

Rubicon should provide a simple mechanism for casting objects into different (but compatible) types.

**Describe the solution you'd like**

Something like the following should be possible:
```
typecast_object = java_cast(generic_object, MyJavaClass)
```

which would convert the `java.lang.Object` instance `generic_object` into the `MyJavaClass` instance `typecast_object`. `typecast_object` could then be used anywhere that a `MyJavaClass` argument is required.

**Describe alternatives you've considered**

This can be achieved manually; e.g., in the Android Clipboard example:
```
from rubicon.java.jni import java

tmp = self._native_activity.getSystemService("clipboard")
clipboard_manager = android.ClipboardManager(__jni__=java.NewGlobalRef(tmp))
```

where `ClipboardManager` is an instance of `JavaClass('android/content/ClipboardManager')`.

**Additional context**

This example code implicitly creates a global JNI reference; it might be desirable to make local/global referencing an option.

### PR DESCRIPTION
**Pull request by freakboy3742**
Allows a Java object reference to be cast to another class using the `__cast__()` 

`obj.__cast__(Thing)` will cast the instance `obj` to the JavaClass `Thing`. 

`obj.__cast__(Thing, globalref=True)` will cast the instance `obj` to the JavaClass `Thing`, and make the resulting object a global JNI reference.

(Note: This PR builds on #63)

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by t-arn** [comment]
Why are you naming the method __cast__() and not just cast() as it is in java.lang.Class?

What exactly is the effect of NewGlobalRef?

**Comment by t-arn** [comment]
Will the cast also work when the object to be casted is an array of some Java type?

**Comment by freakboy3742** [comment]
Huh... I actually didn't know about `Class.cast()` - I've always treated casting as a compile-time concern. However, ironically, the reason for using `__cast__` was specifically to avoid namespace collision - "dunder" is a Pythonic language convention, so it's unlikely to collide with a Java API. 

My argument would be that `__cast__()` is the linguistic mapping of a compile-time typecast (in Java - `MyObject x = (MyObject) y`), whereas `.cast()` is a runtime cast (`MyObject x = MyObject.cast(y)`). In terms of implementation, the "compile-time" typecast will be faster, because it's not going through a JNI function call - it's just reallocating an existing JNI reference to a different Python-side wrapper.

As for NewGlobalRef: JNI has 2 types of object references - local and global. References are local by default; but local references become invalid when the execution returns from the native method in which the local reference is created. Global references persist across the JVM. We occasionally need global references when we need to persist references to objects - see, for example, the scroller in DetailedList view. I don't have any specific use case for the `globalref` argument in mind, but given that we're manipulating JNI references, it made sense to me to include the "upgrade".

The interaction with Arrays is more interesting. At present, we convert arrays on input - so Python lists get converted to a Java array in the function call - so there's no Java representation of an array, and thus nothing to cast. The conversion in the function call looks at the type of the first item in the array to determine typing, so I guess you'd need to cast the first item of the array to the type you want. I guess we'd need to introduce an array wrapper if we wanted to do something more. 

Do you have a specific use case in mind for this functionality?

**Comment by t-arn** [comment]
No, at present, I don't have a specific use case for casting arrays

**Pull request merged**
